# Generated by Django 5.2.15 on 2026-06-19 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_auto_20200416_0053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='StudyArea',
        ),
    ]
