# For development use

version: '3'
services:
  frontend:
    image: electricmagnetic/keadatabase_frontend
    build: ./frontend
    working_dir: /home/node
    ports:
      - 3000:3000
    volumes:
      - './frontend:/home/node'
      - '/home/node/node_modules'
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  about:
    image: electricmagnetic/keadatabase_about
    build: ./about
    working_dir: /home/node
    ports:
      - 3001:3001
    volumes:
      - './about:/home/node'
      - '/home/node/node_modules'
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  backend:
    image: electricmagnetic/keadatabase_backend
    restart: always
    build: ./backend
    working_dir: /app
    command: ["python3", "src/manage.py", "runserver", "0.0.0.0:8000"]
    environment:
      - 'DATABASE_URL=postgres://postgres:keadatabase@database:5432/keadatabase'
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgis/postgis
    environment:
      - POSTGRES_DB=keadatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=keadatabase
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
