# Generated by Django 5.2.15 on 2026-06-18 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_auto_20200416_0053'),
        ('surveys', '0007_alter_survey_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='max_flock_size_grid_tile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.gridtile'),
        ),
    ]
