# Generated by Django 5.2.15 on 2026-07-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_observer_user_optional_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='purpose',
            field=models.CharField(blank=True, choices=[('', ''), ('tunnel', 'Tracking Tunnel Check'), ('fwf', 'FWF Hunting'), ('hunt', 'Hunting'), ('guide', 'Guiding'), ('trap', 'Trapping'), ('permolat', 'Permolat/Hut/Track Work'), ('tramp', 'Tramping'), ('research', 'Researching'), ('kea', 'Kea Surveying'), ('hut', 'Hut Wardening'), ('cycle', 'Bike/Cycle Touring'), ('walking', 'Walking'), ('other', 'Other')], default='', max_length=15),
        ),
    ]
