import Head from "next/head";
import dynamic from "next/dynamic";

import { Loader } from "components/utilities";

const BaseMap = dynamic(() => import("components/map/base"), {
  ssr: false,
  loading: () => <Loader />,
});

export default function Home() {
  return (
    <div style={{ height: "100%", width: "100%" }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BaseMap />
    </div>
  );
}
