import Head from "next/head";
import dynamic from "next/dynamic";

import { Loader } from "components/utilities";

const HomeMap = dynamic(() => import("components/views/HomeMap"), {
  ssr: false,
  loading: () => <Loader />,
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeMap />
    </>
  );
}
