# Generated by Django 3.2.15 on 2022-10-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0038_auto_20220719_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonsighting',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('public', 'Verified (Public)'), ('Private', (('private', 'Verified (Private)'), ('bad', 'Bad (Private)'))), ('Special', (('fwf', 'FWF Observation'), ('kct', 'KCT Observation'), ('nztf', 'NZTF Observation'), ('captive', 'Captive Observation'))), ('Automated', (('radio', 'Radio Tracking Observation'), ('camera', 'Trail Camera Observation')))], default='new', help_text='Moderator: confirm verification and private/public status', max_length=10),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('public', 'Verified (Public)'), ('Private', (('private', 'Verified (Private)'), ('bad', 'Bad (Private)'))), ('Special', (('fwf', 'FWF Observation'), ('kct', 'KCT Observation'), ('nztf', 'NZTF Observation'), ('captive', 'Captive Observation'))), ('Automated', (('radio', 'Radio Tracking Observation'), ('camera', 'Trail Camera Observation')))], default='new', help_text='Moderator: confirm verification and private/public status', max_length=10),
        ),
    ]
