# Generated by Django 3.2.15 on 2022-10-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0039_auto_20221004_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='activity',
            field=models.CharField(blank=True, choices=[('', ''), ('tourist', 'Tourist'), ('local', 'Local'), ('school', 'School Group'), ('community', 'Community Group'), ('skier', 'Skier'), ('tramper', 'Tramper'), ('hunter', 'Hunter'), ('birder', 'Birder'), ('climber', 'Climber'), ('doc', 'DOC Staff'), ('research', 'Researcher'), ('other', 'Other')], default='', max_length=15),
        ),
    ]
