name: frontend

defaults:
  run:
    working-directory: frontend

on:
  push:
    branches: [main]
    paths:
      - "frontend/**"
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
          run_install: |
            - cwd: frontend
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: frontend/pnpm-lock.yaml
      - run: npx prettier --check src/ public/
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm test
