name: survey

defaults:
  run:
    working-directory: survey

on:
  push:
    branches: [main]
    paths:
      - "survey/**"
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
          run_install: |
            - cwd: survey
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: survey/pnpm-lock.yaml
      - run: pnpm install
      - run: pnpm dlx prettier@latest --check src/ public/
      - run: pnpm run build
      - run: pnpm test
